/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(navtex_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ad6b01889f8a75cb036c65af2477aa76)
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/navtex/navtex_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <navtex_decoder_pydoc.h>

template <typename T>
void bind_navtex_decoder_template(py::module& m, const char* classname)
{
    using navtex_decoder    = gr::navtex::navtex_decoder<T>;

    py::class_<navtex_decoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<navtex_decoder>>(m, classname, D(navtex_decoder))
        .def(py::init(&gr::navtex::navtex_decoder<T>::make),
             py::arg("sampling_rate"),
             py::arg("filename") = nullptr,
             py::arg("reverse") = false,
             D(navtex_decoder, make)
        );
}

void bind_navtex_decoder(py::module& m)
{
    bind_navtex_decoder_template<std::int16_t>(m, "navtex_decoder_s");
    bind_navtex_decoder_template<float>(m, "navtex_decoder_f");
}
